### ISSUE TITLE
currentSrc

### ISSUE THREAD

**Issue by michaelminter** [eXon/videojs-youtube#103]
Problem getting VAST plugin to work with youtube plugin

currentSrc is used by the videojs-ads plugin several times to keep track of the preroll video.

Which means that the youtube plugin doesn't implement the currentSrc api method.

original issue: https://github.com/theonion/videojs-vast-plugin/issues/15#issuecomment-41570950

**Comment by kipotlea** [comment]
@AramZS  : is you have  try use VAST plugins and. Youtube plugins work together?
