### ISSUE TITLE
In internet explorer 8 not working

### ISSUE THREAD

**Issue by blooesky** [eXon/videojs-youtube#105]
In IE 7 & 8 not working..is black screen and 2 errors 
![js1](https://cloud.githubusercontent.com/assets/7414312/2902693/ae8a8ec6-d5e8-11e3-9f9f-843e2dbf8fb5.jpg)

**Comment by GaryNaj** [comment]
I want to ask if this java script only works for single instance, do I need to edit manually every youtube URL to make it play? What is the difference between this and the video.js from CDN?  I am currently using IE8. Thanks
