### ISSUE TITLE
"No compatible source was found for this video" problem

### ISSUE THREAD

**Issue by NeoCsatornaja** [eXon/videojs-youtube#114]
Hy!
I working a file generator on here for video.js:
http://neocsatblog.mblx.hu/HTML_generator/
Works pretty fine, but your plugin dosen't work.
Here my html file:
http://neocsatblog.mblx.hu/embeds/generated.html

Can you help me please?

**Comment by pardeep7387** [comment]
I am getting Error now "No compatible source was found for this video".

Steps i used to work till now....
1. Downloaded videojs-youtube from https://github.com/eXon/videojs-youtube 
2. installed git, npm, bower on window 10 pro.
3. Run command in Command prompt as directed in Readme.md file.
3. changed local to cdn in head of Simple.html as :
         <script src="http://vjs.zencdn.net/c/video-js.css"></script>
        <script src="http://vjs.zencdn.net/c/video.js"></script>
4. Run file simple.html under Examples Directory.
Anyone can tell me why i am getting this Error on Chrome,Edge, Explorer.


"No compatible source was found for this video".

**Comment by pardeep7387** [comment]
Thanks NeoCsatornaja!
You saved me... After 5 days i found this very helpfull.

**Comment by NeoCsatornaja** [comment]
@pardeep7387 Thx for exon, he give me some ideas for fix the code. :)
