### ISSUE TITLE
YouTube Livestream Support

### ISSUE THREAD

**Issue by ghost** [eXon/videojs-youtube#143]
Could we possibly add YouTube livestream support to this plugin? The new Live videojs state could be used (in vjs 4.6.0) as using the default player is really, really buggy. For example, the progress bar escapes the defined video area.

**Comment by deweydb** [comment]
Sorry for dragging this old thread out of the mud, but testing with this live stream video:
https://www.youtube.com/watch?v=oI3pxPBYLfo

I get an error message saying "A network error caused the video download to fail part-way"

Are you sure that live stream youtube videos work?

**Comment by deweydb** [comment]
Sorry please disregard. problem was resolved by updating to latest version.

**Comment by anzmedia** [comment]
demo  tv channel and youtube live streamer auto update https://www.anzmedia.workers.dev
