### ISSUE TITLE
Poster overwritten on init()

### ISSUE THREAD

**Issue by cameront** [eXon/videojs-youtube#16]
If the video tag has already specified a poster or if the player has a posterImage specified, the plugin shouldn't overwrite the poster.

Would also be great if the poster creation happened in its own function outside of init, to make the behavior more customizeable.

Needing to do some hackish on-initialization-magic to reset the poster right now: http://jsfiddle.net/82yFj/5/

**Comment by mabarros** [comment]
What was the solution for this again? Use the patch above? I'm using the latest and it is not working.
