### ISSUE TITLE
"blocked" error - Android Tablet - http/https, video doesn't start

### ISSUE THREAD

**Issue by ddpunk** [eXon/videojs-youtube#216]
I found a problem on Android Tablet while trying to play youtube with forceSSL. Even when it is set up to TRUE, it says, that player (html5player.js) is trying to get unsecured data.

```
[blocked] The page at 'https://www.youtube.com/embed/05xfYf4cQbE?modestbranding=1&enablejsapi=1&iv…uto&origin=http://localhost:3000&cc_load_policy=0&cc_lang_pref=pl-PL&hl=pl-PL' was loaded over HTTPS, but ran insecure content from 'http://r2---sn-uvt5-ajwe.googlevideo.com/videoplayback?dur=136.320&key=yt5&…palive=yes&ratebypass=yes&mime=video%2Fmp4&c=web&cver=html5&range=0-127105': this content should also be loaded over HTTPS.
```

Video plays when I change forceSSL to FALSE, but behaves strange - only poster is visible.
Problem appears on Chrome 38.0.2125.122 with tablet Galaxy Tab device mode turned on.
video.js ver. 4.9

**Comment by danielcebrian** [comment]
I have the same problem, have you solved @ddpunk ?

**Comment by danielcebrian** [comment]
you can test it even without table with your chrome on Desktop PC. Just go to inspect element and then press swift device (it is an icon of a "tablet") and then you can select whatever device you want (android, ipad, iphone...)
