### ISSUE TITLE
I can't select quality

### ISSUE THREAD

**Issue by NeoCsatornaja** [eXon/videojs-youtube#217]
I have a little issu with mouseover event....
<a href="http://vu2244.s1.bixcp.hu/embeds/dragonage.html">Here</a> a example.
You see?
You can't select the quality, becuse the menu is close, when you whant choice a option.
Tested with:
Chrome latest version, fullhd resolution.

**Comment by blooesky** [comment]
I have same problem ...missing quality selector with videojs version 4.11.2. I removed old files but quality selector missing. Please help me
