### ISSUE TITLE
Video Size Always the Same

### ISSUE THREAD

**Issue by ghost** [eXon/videojs-youtube#221]
Getting a weird sizing error. No matter how large/small I set the video in my markup the actual video within the iframe is set at 300x150.

``` html
<video 
    id="video-id" 
    src="" 
    class="video-js vjs-flat-skin" 
    controls preload="auto" 
    width="640" 
    height="360" 
    data-setup='{ 
        "techOrder": ["youtube"], 
        "quality": "720", 
        "forceHTML5": false,
        "src": "https://www.youtube.com/embed/aIMgfBZrrZ8" 
    }'>
</video>
```

![video-error](https://cloud.githubusercontent.com/assets/1456472/5203479/394ef11e-7544-11e4-9653-aae6683c85f5.png)

The size of the video.js container is correct, but the video itself is not.

Any ideas?

**Comment by craigathon** [comment]
To anyone else with this issue, the cause for me was my custom css I had implemented for responsive videos. I had success with this css for responsive instead.

.vjs-youtube { 
	position: relative; 
	padding-bottom: 56.25%; 
	height: 0; 
	overflow: hidden; 
	max-width: 100%; 
} 

.vjs-youtube iframe { 
	position: absolute; 
	top: 0; 
	left: 0; 
	width: 100%; 
	height: 100%;
}
