### ISSUE TITLE
Quality selector is missing.

### ISSUE THREAD

**Issue by Ampelmann23** [eXon/videojs-youtube#233]
The qualitys are missing.

**Comment by blooesky** [comment]
I have same problem. And if i replay....vjs-big-play-button remains over video  ...

**Comment by Ampelmann23** [comment]
@blooesky - You can fix your bug with CSS or JS.

**Comment by eXon** [comment]
I will take a look at this soon. It's probably quick to fix. Can you give me your browser/OS specs, the way to replicate and any additional information that might be relevant? Thank you

**Comment by Ampelmann23** [comment]
This is very nice, thank you. Operating system: Win 8.1 | Browser: G. Chrome, Vers. 39.0.2171.95 m. I think YouTube change something on the player that is the reason why the qualities are missing. I would be interesting to know what the problem really is.

**Comment by eXon** [comment]
Should work now

**Comment by Ampelmann23** [comment]
Thanks, that you take time for troubles. :+1:  It would be well if there are more of those peoples...
