### ISSUE TITLE
After replay The big play button stays visible over video 

### ISSUE THREAD

**Issue by blooesky** [eXon/videojs-youtube#236]
If i want to Replay video The big play button stays visible over video 
when is playing  that only if i push on big button for replay 
else if i push  little play button from controls bar for replay the big button will be hidden.

![11](https://cloud.githubusercontent.com/assets/7414312/5834855/53875e20-a16a-11e4-943f-0e1005f41d0f.jpg)

**Comment by eXon** [comment]
Please describe how to reproduce and an example

**Comment by blooesky** [comment]
when the video ends show the big play button. If i press him video replaying but the big button not hidden. He will hidden only i press "play" from controls bar.

**Comment by mahakala** [comment]
when i press the big button, the spinner shows up and only when the video stars the button hides. can't the button just hide after one click?

**Comment by blooesky** [comment]
How we can fix this? button is not hidden at replay

**Comment by eXon** [comment]
This has been fixed with the last version of VJS / YouTube tech
