### ISSUE TITLE
Problem Event Play/Pause

### ISSUE THREAD

**Issue by carbos10** [eXon/videojs-youtube#238]
I use videoJS's API, i included this plugin, but when i go to pause, i have play event, but when the video is play, it calls pause event.
```
myPlayer.on('pause', function(){
				checkPausePlay();
			});
			myPlayer.on('play', function(){
				checkPausePlay();
			});
			myPlayer.on('seeked', function(){
				//code 
			});
```
this is my code

I check the pause or play with:
```
var checkPausePlay = function() {
                var isPaused = myPlayer.paused();
				var time_video = myPlayer.currentTime();
                if(isPaused === true) {
                    // code
                } else {
			// code
				}
            };
```

**Comment by eXon** [comment]
Just tested your code and my play/pause events are working fine. Only play or pause is called. It might be a fix with the last VJS version
