### ISSUE TITLE
Errors with 'out of the box' downloaded example code

### ISSUE THREAD

**Issue by compumatter** [eXon/videojs-youtube#240]
Hello,

Downloaded and extracted the code. FIrst, your example code assumers bower is installed. I do not.  So I changed the head tag to the following:
<!DOCTYPE html>
<html>
<head>
  <link type="text/css" rel="stylesheet" href="http://vjs.zencdn.net/4.11/video-js.css" />
  <script src="//vjs.zencdn.net/4.11/video.js"></script>
  <script src="/ytjs-test/src/youtube.js"></script>
</head>

Then, I ran your file exactly as is.  Got the following error in Firefox firebug console.  The video played, but spawned two errors.  
![youtube-js-error](https://cloud.githubusercontent.com/assets/121611/6005786/e5139236-aac1-11e4-804f-15b69fa9fffe.png)

I replicated this with simple.html, autoplay.html and the sandbox/index.html.  I did not go further as clearly something is wrong.  I also changed permissions on the file structure to chmod 777 in case there was some surprise writing going on but that had no effect.

Any ideas what is going wrong here ?

**Comment by eXon** [comment]
This has nothing to do with the plugin. The examples all work on every browsers and OS as expected. If you find a way to replicate a new bug, please fill a new issue with more details
