### ISSUE TITLE
when will vjs-youtube update to latest video.js?

### ISSUE THREAD

**Issue by mahakala** [eXon/videojs-youtube#243]
as said - when will it update?

vs is v4.11.4  now, youtube works with 4.6 :( and causes errors when updating to the latest

**Comment by watdafox** [comment]
it's compatible 4.11, I use it

**Comment by mahakala** [comment]
have a link to a demo?

**Comment by watdafox** [comment]
https://git.popcorntime.io/popcorntime/desktop/tree/nw11

Oh, you should note that I don't use vjs-youtube release, but a snapshot from dev builds.

**Comment by mahakala** [comment]
ah. ok, thanks

**Comment by eXon** [comment]
A new release will be pushed in the upcoming week. I know it's been a while
so I'll try to take care of that quick

**Comment by mahakala** [comment]
wow! thanks :)
