### ISSUE TITLE
Initialize videojs on an existing Youtube iframe

### ISSUE THREAD

**Issue by denisvlr** [eXon/videojs-youtube#248]
I need to instantiate a videojs object based on an existing Youtube Iframe (that has already been created in the dom), in order to control it with videojs methods and events. In order words it shouldn't affect the dom, just return the player object to call ```player.play()``` for instance.

If I were using directly the Youtube API, I would simply do:
```var player = new YT.Player('<<iframe_id>>');```

However with videojs it doesn't seem to be possible, the init method destroys the iframe.

Is there any way to do it? What would be the best approach to implement such a feature? I'm willing to contribute with a PR but a few tips would be helpful :) 

I'm in an environment where I don't control how videos have been initialized, and other parts of the code might already use the Youtube iframe.
Thanks!

**Comment by eXon** [comment]
You can simply get the URL of the iframe, destroy or hide it and simply pass it to VJS

**Comment by eXon** [comment]
We don't plan to support this. If you need further assistance, don't hesitate.
