### ISSUE TITLE
Not allowed to run on samsung tablet or smartphones

### ISSUE THREAD

**Issue by danielcebrian** [eXon/videojs-youtube#249]
Any clue on that?. It is the same issue as https://github.com/eXon/videojs-youtube/issues/216. 

There is a blocker issue with https and http that I don't understand.

To see the error just go to inspect element and then press swift device (it is an icon of a "tablet") and then you can select whatever device you want (android, ipad, iphone...), my problem is using samsung devices as samsung galaxy Tab 10

Could someone help me?

Thank you

**Comment by eXon** [comment]
This one is tricky.

Using HTTPS inside a HTTP page shouldn't trigger a mixed content error. This should be fixed by YouTube. If we detect the user protocol and use HTTP, those logged in with their Google accounts will still be using HTTPS (this is weird I know) and it will crash.
