### ISSUE TITLE
Getting thread blocking executions, what can I do?

### ISSUE THREAD

**Issue by aaronharding** [eXon/videojs-youtube#250]
I'm creating a single page app and using videojs along with this plugin to play a single YouTube video. The page hangs a far amount since it is a 6 section single pager with some heavy images on the first page. It hangs for ~2 seconds in total, although when I comment out the instance of videojs with this plugin, it hangs for about ~400ms. Here is the main thread using videojs and then without:

![screen shot 2015-03-25 at 11 09 45](https://cloud.githubusercontent.com/assets/1704000/6822414/dc1fc4ce-d2df-11e4-910b-18b8b7f11d0b.png)

and after, without the instance of videojs-youtube:

![screen shot 2015-03-25 at 11 10 24](https://cloud.githubusercontent.com/assets/1704000/6822420/e304ca8c-d2df-11e4-8edc-a73a639cef38.png)

Can you recommend anything to help debug the page freeze? My inline HTML is:

    <video id="trailer" preload="false" class="video-js vjs-default-skin" controls preload="auto" width="auto" height="auto" data-setup='{ "controls": true, "autoplay": false, "preload": false, "quality" : "240p", "techOrder": ["youtube"] }'>
        <source src="http://www.youtube.com/watch?v=DQaeRCvxF1E" type='video/youtube' />
    </video>

**Comment by eXon** [comment]
Most of the stuff that takes your CPU is inside the YouTube iframe and their API. Their is not much we can do about it.

Have you compared using videojs + youtube plugin and using the embeded youtube code?

**Comment by eXon** [comment]
Please send more informations if you are still having this problem.
