### ISSUE TITLE
having problems playing yt-playlists

### ISSUE THREAD

**Issue by michapixel** [eXon/videojs-youtube#252]
it seems this feature isn't working for me. 

this list doesn't work at all:
http://www.youtube.com/playlist?list=PLA60DCEB33156E51F

this plays the first video only, then stops and if you hit play again it plays the next. 
http://www.youtube.com/watch?v=xjS6SftYQaQ&list=SPA60DCEB33156E51F

**Comment by eXon** [comment]
I fixed the problem that it stops after every video.

I'm working on making http://www.youtube.com/playlist?list=PLA60DCEB33156E51F work. It's a little bit more tricky.
