### ISSUE TITLE
Issue with setting className

### ISSUE THREAD

**Issue by mulhoon** [eXon/videojs-youtube#254]
I seemed to be getting an```null``` player error when updating the source manually.

To fix it I changed this
Line 60: ```this.playerEl_ = document.getElementById(player.id());```

to this...
Line 60: ```this.playerEl_ = player.el();```

Not sure if this is an improvement, but just thought I'd throw it your way.

Great plugin.
N

**Comment by eXon** [comment]
Great catch thank you for noticing and reporting :+1:
