### ISSUE TITLE
Not working with Videojs 4.12.5

### ISSUE THREAD

**Issue by cnsgcu** [eXon/videojs-youtube#255]
It seems this plugin is not working with the current version of Videojs. Can you confirm if this is working with videojs 4.12.5?

Edit: Figured out. It's not working because I was using ReactJS to render the video component and ReactJS prevented DOM transformation of the plugin.

**Comment by eXon** [comment]
I don't think there is any ReactJS support for Video.js. It rely way too much on DOM manipulation and it will clash with the virutal DOM.

**Comment by stopspazzing** [comment]
I'm having same issue, even using your example files, video won't load. Have tried 4.12.6 without success.
