### ISSUE TITLE
Quality Names are Incorrect

### ISSUE THREAD

**Issue by ThomasMorrison** [eXon/videojs-youtube#257]
This is a small oversight but it would be nice if the quality names matched 1 - 1 with the ones shown on the actual youtube player:

Youtube
![screen shot 2015-04-17 at 10 30 05 am](https://cloud.githubusercontent.com/assets/4522962/7203987/db103c66-e4ec-11e4-8294-95f1c681c8cc.png)

videojs-youtube
![screen shot 2015-04-17 at 10 32 06 am](https://cloud.githubusercontent.com/assets/4522962/7204010/0c23d6f0-e4ed-11e4-82c0-65803fbc24ad.png)
(No HD labels, Auto isn't capitalized & Auto doesn't mention the current "suggested" quality)

Solutions
---
* Swapping the names to match
* Allowing `convertQualityName` & `parseQualityName ` to work off of a user definable object, this is the better solution as it allows users to perform their own localisation.

**Comment by eXon** [comment]
I think you are correct. It would be better to be as close as possible to
youtube

**Comment by eXon** [comment]
Fixed with #258
