### ISSUE TITLE
Can't play this specific video

### ISSUE THREAD

**Issue by AlicanC** [eXon/videojs-youtube#260]
The video I am trying to play is this:
https://www.youtube.com/watch?v=M7lc1UVf-VE

I can't provide my exact code, but I was able to reproduce this using the example in the README:
- Clone the repo
- Run grunt
- Create a "test.html" in "dist" directory and put this example code in it:
```html
<!DOCTYPE html>
<html>
<head>
  <link type="text/css" rel="stylesheet" href="https://vjs.zencdn.net/4.12/video-js.css" />
  <script src="https://vjs.zencdn.net/4.12/video.js"></script>
  <script src="vjs.youtube.js"></script>
</head>
<body>
  <video id="vid1" src="" class="video-js vjs-default-skin" controls preload="auto" width="640" height="360" data-setup='{ "techOrder": ["youtube"], "src": "http://www.youtube.com/watch?v=xjS6SftYQaQ" }'>
  </video>
</body>
</html>
```
- Replace "xjS6SftYQaQ" with "M7lc1UVf-VE"
- Start an HTTP server in "dist" directory
- Go to "test.html"
- Poster is there but the video won't play.

**Comment by eXon** [comment]
Do you have anything in the console?

**Comment by AlicanC** [comment]
Sadly, I don't have anything. Were you able to reproduce?

**Comment by eXon** [comment]
I haven't tried yet, I'll see what I can do this week

**Comment by eXon** [comment]
@AlicanC on what OS/browser are you? I'm on linux / Chrome and it is working perfectly fine.

**Comment by AlicanC** [comment]
- Win 8.1 Enterprise - Chrome - Fail
- Win 8.1 Enterprise - Firefox - OK
- Server 2012 R2 Datacenter - Chrome - OK
- Ubuntu 14.10 on Hyper-V Gen 2 - Chrome - OK
- Ubuntu 14.10 on Hyper-V Gen 2 - Firefox - OK

I'd assume something is wrong with my Chrome.

This is the network panel for 8.1:
![On Windows 8.1 Enterprise](http://snaps.alicanc.com/2015-04-21_135944.png)

And this is the network panel for 2012 R2:
![On Windows Server 2012 R2](http://snaps.alicanc.com/2015-04-21_140102.png)

8.1 is sure missing some stuff. Sometimes the play button is disabled and sometimes I can click it. When I do, the loading spinner shows up and keeps spinning.

8.1 and 2012 R2 syncs with my Google account so I don't think anything is wrong with extensions. (Though I still tried disabling them.)

It's weird that this only happens on my 8.1 and only this specific video causes the problem. (Maybe there are more, but I haven't found any yet.)

If you have any ideas, please let me know. You can close this otherwise and I'll post here if I find something.

**Comment by AlicanC** [comment]
Doesn't occur anymore.
