### ISSUE TITLE
After end of playback button "play" doesn't becomes a triangle

### ISSUE THREAD

**Issue by Dotrox** [eXon/videojs-youtube#261]
After end of playback video from YouTube button "play" doesn't becomes a triangle (remains the stripes).

Vjs 4.12.5

Firefox 37.0.2
Chrome 42.0.2311.135

**Comment by itsvee** [comment]
I try to edit code in youtube.js line 697
```
if (stopPlaying) {
// Replace YouTube play button by our own
     if(!this.player_.options()['ytcontrols']) {
          this.playerEl_.querySelectorAll('.vjs-poster')[0].style.display = 'block';
          if(typeof this.player_.bigPlayButton !== 'undefined') {
                this.player_.bigPlayButton.show();
          }
     }
     this.player_.trigger('ended'); // this line
}
```
change `ended` is `pause` it's work! You can try.

**Comment by Dotrox** [comment]
I am already did this. However I am simply added `this.player_.trigger('pause');` before `this.player_.trigger('ended');` and it works.
But I think this is a hack and might be another solution.

**Comment by eXon** [comment]
The pause is now automatically triggered right before the ended event. It seems to be a glitch with VJS when calling multiple play events. Will need to check further in case I need to fix this on the core.

**Comment by Dotrox** [comment]
This fix doesn't work.

**Comment by eXon** [comment]
Does the new one work? I did a new one

**Comment by Dotrox** [comment]
Yes, this works and I am already using it :)  (see https://github.com/eXon/videojs-youtube/issues/261#issuecomment-101618541)
