### ISSUE TITLE
Use speed controls while streaming from youtube

### ISSUE THREAD

**Issue by donpinkus** [eXon/videojs-youtube#262]
Hey there - great plugin!

I'm trying to add speed controls that range from 25% (0.25x) speed up to 1,000% speed (10x).  Pretty straightforward with video.js, but will this speed control work with a Youtube video?

**Comment by eXon** [comment]
Hey Don,

I don't think it would work. However, it would be pretty easy to fix. The
YouTube API has that capability (setPlaybackRate).

**Comment by donpinkus** [comment]
Interesting, do we know what playback rates Youtube supports? I can see from their player it has 0.25 - 2x, but not sure it has 10x. 

If it does I can make the PR

**Comment by eXon** [comment]
Now supported

**Comment by alsar** [comment]
How do I use this? I tried `"playbackRates": [0.5, 1, 1.5, 2],` in data-setup, but it has no effect.

**Comment by eXon** [comment]
@alsar Video.js let you change the playback rates, this is not a YouTube specific feature. Use by javascript `playbackRate(0.5)` or use a plugin that show a menu (if it's what you want)

**Comment by alsar** [comment]
@eXon I wanted to show the rates in the menu, but it doesn't show them. 

```html
<video class="video-js vjs-default-skin embed-responsive-item"
           controls
           preload="auto"
           data-setup='{
                "playbackRates": [0.5, 1, 1.5, 2],
                "techOrder": ["youtube"],
                "src": "http://www.youtube.com/watch?v=jFnqQbtHeDE"
           }'>
</video>
```
