### ISSUE TITLE
Double Click for fullscreen mode

### ISSUE THREAD

**Issue by itsvee** [eXon/videojs-youtube#263]
Hi there,

I found some options in plugin. If I double click on video player, video will fullscreen and show YouTube player. Can I disable it ? Thanks a lot. :)

**Comment by eXon** [comment]
You can now set the option `ytFullScreenControls` to `false`. Will be in the next release soon.

**Comment by varemenos** [comment]
I've checked the source code but haven't found any loc relevant to this.
Is this feature included in videojs-youtube? If not can we have the issue reopened?

**Comment by ImranBugCMG** [comment]
Full screen on double click isn't working.
