### ISSUE TITLE
Ask plugin if given source is supported url format

### ISSUE THREAD

**Issue by pgtaboada** [eXon/videojs-youtube#265]
hi,

video.js asks via "canPlay" if a given source object can be played. I would like to extend that method so that if no type is provided, a reggex is used.

Is there any way to easily implement this, so I don't have to duplicate the test code?

for the vimeo plugin I solved it this way:

```javascript
videojs.Vimeo.canPlaySource = function(srcObj){
  if (srcObj.type)  
      return (srcObj.type == 'video/vimeo');
  else {
      var regExp = /^.*(vimeo\.com\/)((channels\/[A-z]+\/)|(groups\/[A-z]+\/videos\/))?([0-9]+)/;
      var match = srcObj.src.match(regExp);

      return (match)
  }
};
```

**Comment by eXon** [comment]
This seems to have changed quite a bit on the core. I'll have to check how we can handle that.

**Comment by pgtaboada** [comment]
Did it? 

Actually, Video.js asks the plugin if it can play a given source. The current implementation only checks the source type, but not the src.

**Comment by eXon** [comment]
I was trying to check when `canPlaySource` is called and your else will never happen. The reason is if we don't have a type, it will not even check. It makes sense for regular videos but not for 3rd party services.

I think I know a great way to do that so I will propose a fix to them so `canPlaySource` can get called and we'll see what they think.

**Comment by eXon** [comment]
In the mean time, you can specify your type (video/youtube or video/vimeo) so the tech are changed.

**Comment by pgtaboada** [comment]
It get's called when you add child source elements, and not when you set src in the video element.

**Comment by eXon** [comment]
It will get called only if you specify the type like that:

```javascript
player.src({ type: 'video/youtube', src: 'https://www.youtube.com/watch?v=7MAVG2BfTHc' });
```

I am doing a PR that will let tech like YouTube take over when their is a youtube URL but for now it is impossible.
