### ISSUE TITLE
Needs support for 1440p & 2160p

### ISSUE THREAD

**Issue by stopspazzing** [eXon/videojs-youtube#270]
https://www.youtube.com/watch?v=rdQ0i3v_KVY&list=PL5BF9E09ECEC8F88F&index=5
shows auto where 1440 and 2160 are located.

My test wordpress site (ignore styling issue not related) if you want to see the issue:
http://dev.stopspazzing.com/

**Comment by eXon** [comment]
It has been already fixed on the master

**Comment by stopspazzing** [comment]
I used composer to install this plugin, which is the one on the site, doesn't it pull from master?

**Comment by eXon** [comment]
video.js is on composer but I don't think videojs-youtube is. How did you get it?
