### ISSUE TITLE
Update source

### ISSUE THREAD

**Issue by johnfumaster** [eXon/videojs-youtube#271]
Hi, how can I update the source of the player?  I managed to do this, but the duration bar does not update, so I suspect I'm not doing it right?

```
var $vidObj = videojs('videodiv');
$vidObj.src({ src: '//youtu.be/' + youtubeID });
$vidObj.load();
$vidObj.show();
$vidObj.play();

**Comment by eXon** [comment]
You can check the javascript example:

`player.src('http://www.youtube.com/watch?v=jofNR_WkoCE');`
