### ISSUE TITLE
Iframe blocker make perfomance hit

### ISSUE THREAD

**Issue by mogadanez** [eXon/videojs-youtube#273]
opacity, even very small create extra layers composition
It very sensitive for high quality 60fps videos.
![screen](http://i.imgur.com/gNptHY7.png)

**Comment by eXon** [comment]
You are absolutely right. We should find another way than using opacity to 0.01. I'll check what might be better for performance and still catch the mouse events.

**Comment by zowers** [comment]
looks like iframeblocker is used solely to respond to click events to implement pause/play.
but the play/pause is implemented by youtube themselves, so it can be used instead
`onStateChange() ` can be used to subscribe to the events
https://developers.google.com/youtube/iframe_api_reference#onStateChange

**Comment by mogadanez** [comment]
also, looks like youtube agreement not allow it 
```
"F. If you use the Embeddable Player on your website, you may not modify, build upon, or block any portion or functionality of the Embeddable Player, including but not limited to links back to the YouTube website."
```

**Comment by eXon** [comment]
@zowers We are using the iframe blocker only to catch when the mouse is over the player for the navigators that doesn't support `pointer-events: none;` (IE and mobile), then it disappear. It is not about the play/pause events.

@mogadanez We are not altering in any way the YouTube player. The YouTube watermark is still there and no functionality has been changed. The iframeblocker is only about detecting when your mouse is over the video.

**Comment by mogadanez** [comment]
@eXon 

```
  if(/MSIE (\d+\.\d+);/.test(navigator.userAgent)) {
        var ieVersion = Number(RegExp.$1);
        this.addIframeBlocker(ieVersion);
      } else if(!/(iPad|iPhone|iPod|Android)/g.test(navigator.userAgent)) {
        // the pointer-events: none block the mobile player
        this.el_.className += ' onDesktop';
        this.addIframeBlocker();
      }
```
first condition is for IE,  
but second one check that it is NOT mobile, my chrome pass the check and create an iframeBlocker

**Comment by zowers** [comment]
mousemove used to detect and set userActive is needed only when controls are shown

**Comment by mogadanez** [comment]
@zowers means that controls can be disabled. and at least in this case bblockerblockrr ceation can be skipped

**Comment by eXon** [comment]
My bad I meant not mobile.

We can certainly disable that if the VJS controls are not shown.

**Comment by zowers** [comment]
> We can certainly disable that if the VJS controls are not shown.
that will fix performance issue only in this case

**Comment by zowers** [comment]
so how was it fixed?
