### ISSUE TITLE
Disable advertisement (enable enhanced privacy)

### ISSUE THREAD

**Issue by evgenyshev** [eXon/videojs-youtube#274]
Many people know that to turn off advertising in video, simply turn on the increased privacy. How to do it in your plugin?

**Comment by evgenyshev** [comment]
Note Links https://www.youtube-nocookie.com/embed/7MBXocJC-PQ nothing.

**Comment by eXon** [comment]
If you want to disable advertisment, you have to disable it directly within YouTube (turn off monetization). If you are not the owner of the video, it is not up to you to decide.
