### ISSUE TITLE
Grayscale thumbnail

### ISSUE THREAD

**Issue by tenq** [eXon/videojs-youtube#275]
hi, how do I convert youtbe thumbnails on grayscale. I try use a vjs-poster version, but not work. Only work when put -webkit-filter: grayscale(100%); in style clause. How use like class:

````
.gray img
{
	filter: grayscale(1);
	-webkit-filter: grayscale(1);
	-moz-filter: grayscale(1);
	-o-filter: grayscale(1);
	-ms-filter: grayscale(1);
}

.gray img:hover
{
	filter: grayscale(0);
	-webkit-filter: grayscale(0);
	-moz-filter: grayscale(0);
	-o-filter: grayscale(0);
	-ms-filter: grayscale(0);
}


<div class="vjs-poster gray " tabindex="-1" style="background-image: url(https://img.youtube.com/vi/zdDi7pf26i4/maxresdefault.jpg);"></div>

```

**Comment by eXon** [comment]
The problem you are facing is because we are using a background-image instead of an img. I should fix that.

**Comment by eXon** [comment]
After checking with VJS, it is not only because of the plugin but because of the way VJS sometime use background images and sometime images. You should apply to the background-image instead.
