### ISSUE TITLE
VJS 5: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by ange007** [eXon/videojs-youtube#279]
Hello.
In case of initialization of a plug-in in videojs **5.0rc2** there is an error: **Cannot read property 'extend' of undefined**

At line: 
```javascript
videojs.Youtube = videojs.MediaTechController.extend({**});
```

**Comment by eXon** [comment]
The YouTube extension is far from being ready for VJS 5 yet.

**Comment by moay** [comment]
This seems to be fixed in the VJS5 branch.
