### ISSUE TITLE
Reset video time to zero when ended

### ISSUE THREAD

**Issue by itsvee** [eXon/videojs-youtube#281]
I want to reset current time of video is zero when video ended. Can I write or edit code anywhere ? Thanks a lot.

**Comment by eXon** [comment]
You can do something like this using the video.js API:

```javascript
var video = $('#video1');
video.on('ended`, function() {
  video.currentTime(0);
});
```

**Comment by itsvee** [comment]
I try your code. When video end and time reset to zero, It doesn't stop and play continuos. I want to reset time and stop it.
