### ISSUE TITLE
fallback image url not working.

### ISSUE THREAD

**Issue by diegoquispe-vumble** [eXon/videojs-youtube#282]
For videos that don't have a maxresdefault.jpg, the fallback url "https://img.youtube.com/vi/"+id+"/0.jpg" is not working. So, when the video doesn't have a maxres image, no poster is shown.

**Comment by eXon** [comment]
what is your browser / OS?

**Comment by diegoquispe-vumble** [comment]
Running Chrome Version 43.0.2357.130 (64-bit) on OSX 10.9.1
