### ISSUE TITLE
Full screen is not work on ipad

### ISSUE THREAD

**Issue by khoachung89** [eXon/videojs-youtube#283]
I have setup videojs-youtube on my website and everything ok but the full screen function doesn't work on iPad (Safari & Chrome). At first, i think it's an issue of my website code but i have try downloading your fresh example and try. It doesn't work too.
I have modified your example: http://www.mediafire.com/download/is0gcrce986ide1/videojs-youtube-fullScreen.zip
just open the file simple.html in examples folder. The top 2 video which using videojs-youtube cannot run full-screen on ipad. The last video which using a mp4 video source is ok.

I just try to call the function requestFullscreen() of video.js by another button but it cannot work too.

As far as my investigation, i have try adding some attribute like: allowFullScreen="true", webkitallowfullscreen and mozallowfullscreen = "true" also but nothing helps.

My ipad is working on iOS 8.3.

**Comment by khoachung89** [comment]
Could anyone help me out? any workaround solution or any information?

**Comment by Banasura** [comment]
I have the same issue. Have you found a solution?

**Comment by khoachung89** [comment]
Nope, but i think it should be an issue of iOS and Youtube, not videosjs. I have tried other player like JWPlayer and exactly same issue happen. You may also try to open youtube.com on your ipad (remove youtube app if yu installed it) and force Safari request Youtube as desktop. If you click the full screen button, youtube will say, it not support - looks like even youtube cannot do anything better. So, all we can do: just customize to showing the message like that.
