### ISSUE TITLE
Video Js not working for youtube videos

### ISSUE THREAD

**Issue by satyamnigam** [eXon/videojs-youtube#286]
Hi,
I tried videojs-youtube plugin but it is not working in any of the browsers. It only shows the black screen. I have included all the required JS and CSS files. Following is the code snippet of HTML file:
```html
<div>
 <video id="vid1" src="" class="video-js vjs-default-skin" autoplay="autoplay" controls preload="auto"
  data-setup='{ "techOrder": ["youtube", "html5"],     "src":"http://www.youtube.com/watch?v=xjS6SftYQaQ"}'>
  </video>
 </div>
```
Please help me in getting this working.

Thanks,
Satyam Nigam

**Comment by eXon** [comment]
What version of vjs and videojs have you? Care to dumb your html file also?

**Comment by satyamnigam** [comment]
I am using videojs-youtube-1.2.12 and video-js-4.12.11

When I run the examples provided in videojs-youtube-1.2.12, it works fine in a standalone HTML page. But when I run it inside a web application it does not work. Could it be a cross domain issue?

**Comment by crviet92** [comment]
I just do it, it 's normal in chrome and firefox but not ie8 ?
Your code 's true!
(my english 's bad,sorry)

**Comment by crviet92** [comment]
You can insert  <link href="video-js.css" rel="stylesheet" type="text/css">
  <script src="video.js"></script>
	<script src="youtube.js"></script>

**Comment by satyamnigam** [comment]
Please insert code between the tags ```html  and ```

**Comment by crviet92** [comment]
<addr> <link href="video-js.css" rel="stylesheet" type="text/css">
  <script src="video.js"></script>
	<script src="youtube.js"></script></addr>

**Comment by christophelimpalair** [comment]
This happened to me when I had my JS files loaded in the footer. I had to move them to my header.

**Comment by crviet92** [comment]
i think you need include  file youtube.js

**Comment by satyamnigam** [comment]
I have included youtube.js and video.js both.
In the console I can see the below error:
 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by moay** [comment]
I do get this error when using youtube.js for videojs v5 with videojs v4. Or the other way round. Try to check, if you are using the correct version of both.
