### ISSUE TITLE
Uncaught TypeError with playbackRateMenuButton

### ISSUE THREAD

**Issue by christophelimpalair** [eXon/videojs-youtube#288]
I keep getting:
```javascript
Uncaught TypeError: this.player_.controlBar.playbackRateMenuButton.update is not a function
```
It points to this line:
https://github.com/eXon/videojs-youtube/blob/master/src/youtube.js#L662

I thought it was because I was trying to implement playback rates, but I get the same error from a clean install.

I really want the ability the change playback rates but can't get it to work. I'm thinking this error plays a role in this?

**Comment by ANDREYNEMO** [comment]
Has this issue fixed? 
I have the same problem on Video.js v4.5.1 and youtube vjs4

**Comment by TarasKovalyk** [comment]
How it was fixed?
I have the same problem on Video.js v4.5.1 and youtube vjs4

**Comment by gkatsev** [comment]
Video.js 4x and the corresponding version of youtube are no longer officially supported, unfortunately.
