### ISSUE TITLE
It doesnt work well

### ISSUE THREAD

**Issue by VincentSim** [eXon/videojs-youtube#290]
When I play the video It's still below the Image video.
I am using `rails-assets-video.js 4.12.12` and `rails-assets-videojs-youtube 1.2.12`

*My code is :*

`<video id="vid1" src="" class="video-js vjs-default-skin" controls preload="auto" width="640" height="360">
  </video>`

  `<script>
  videojs('vid1', { "techOrder": ["youtube"], "src": "http://www.youtube.com/watch?v=xjS6SftYQaQ","controls": true, });
  </script>`

**Comment by eXon** [comment]
You'll need to be more specific on how to reproduce the bug
