### ISSUE TITLE
VJS5: modestbranding not working

### ISSUE THREAD

**Issue by moay** [eXon/videojs-youtube#292]
I'm testing out the v5 branch with VJS 5.0.0-rc52. The modestbranding option youtube provides seems not to be working. I still get the logo - and it confuses everything... ;-) 

Does anyone know why this doesn't work?

**Comment by moay** [comment]
Seems that `showinfo` and `modestbranding` cannot work together. Ideas on this?

**Comment by eXon** [comment]
mostbranding doesn't hide the YouTube logo in the corner. You cannot do that :(.

**Comment by moay** [comment]
Actually, it does. Try to leave out `showinfo`(just comment it out). But you then have the video information which also isn't the way to go... ;-)
