### ISSUE TITLE
VJS5: YT playbutton is shown 

### ISSUE THREAD

**Issue by moay** [eXon/videojs-youtube#293]
I can't find an option to disable youtubes playbutton. This used to work on VJS4, in the new version it doesn't.

**Comment by moay** [comment]
Okay, found a way around this. How about displaying a poster frame above the player? This does not happen currently, but it would hide the original playbutton.

**Comment by eXon** [comment]
This happens because the VJS5 branch is still under development. VJS5 doesn't allow a tech to set the poster anymore so I have to find a workaround with them. I have to talk with @heff about that issue
