### ISSUE TITLE
VJS5: Chrome fullscreen issues

### ISSUE THREAD

**Issue by moay** [eXon/videojs-youtube#294]
On chrome, I loose the player controls if I enter fullscreen. It works well on safari but doesn't on chrome.

**Comment by moay** [comment]
Ok, updated from VJS 5.0.0 rc52 to rc58. Don't know if this is the fix, but it doesn't happen for the moment... So seems to be fixed.

**Comment by eXon** [comment]
VJS5 branch is still in development. Hopefully I will find some time to finish a first production-ready version soon.

**Comment by eXon** [comment]
Let me know if it comes back
