### ISSUE TITLE
Ready event never fires if the page includes YouTube's iframe_api

### ISSUE THREAD

**Issue by tiffting** [eXon/videojs-youtube#298]
I'm using Video.js with YouTube playback on a site that I don't fully control. This site includes `<script src="https://www.youtube.com/iframe_api"></script>` in its `<head>`, which is preventing the Video.js player from ever triggering its ready event. The consequences include the YouTube video doesn't play when you hit the big play button, and when `dispose()` is run, you get an error about [`qualityButton.parentNode` not existing](https://github.com/eXon/videojs-youtube/blob/master/src/youtube.js#L167) because the player is never ready for the [qualityButton to be added to the DOM](https://github.com/eXon/videojs-youtube/blob/master/src/youtube.js#L132).

Do you have any suggestions as to how to get around this? Below is a prettified dump of the YouTube iframe_api script:

```javascript
if (!window['YT']) {
    var YT = {
        loading: 0,
        loaded: 0
    };
}
if (!window['YTConfig']) {
    var YTConfig = {
        'host': 'http://www.youtube.com'
    };
}
if (!YT.loading) {
    YT.loading = 1;
    (function() {
        var l = [];
        YT.ready = function(f) {
            if (YT.loaded) {
                f();
            } else {
                l.push(f);
            }
        };
        window.onYTReady = function() {
            YT.loaded = 1;
            for (var i = 0; i < l.length; i++) {
                try {
                    l[i]();
                } catch (e) {}
            }
        };
        YT.setConfig = function(c) {
            for (var k in c) {
                if (c.hasOwnProperty(k)) {
                    YTConfig[k] = c[k];
                }
            }
        };
        var a = document.createElement('script');
        a.type = 'text/javascript';
        a.id = 'www-widgetapi-script';
        a.src = 'https:' + '//s.ytimg.com/yts/jsbin/www-widgetapi-vfl3zSWzk/www-widgetapi.js';
        a.async = true;
        var b = document.getElementsByTagName('script')[0];
        b.parentNode.insertBefore(a, b);
    })();
}
```

**Comment by eXon** [comment]
Unfortunally there is no easy fix because VJS and the Website will fight for the onYouTubeIframeAPIReady. If you find a workaround you can create a PR but I don't think there is a safe way to do it.

**Comment by tiffting** [comment]
Okay, thanks!
