### ISSUE TITLE
Uncaught TypeError: Cannot read property 'play' of undefined

### ISSUE THREAD

**Issue by rgw3d** [eXon/videojs-youtube#309]
Unable to play any videos using videojs-youtube.
Testing using the build of videojs on the master and stable branches. 
I am using the examples provided here to test as well.

The full error message when I click to start the video is this:
    Uncaught TypeError: Cannot read property 'play' of undefined
    techCall_ @ player.js:1148
    play @ player.js:1198
    handleClick @ big-play-button.js:46
    ret @ fn.js:35
    119.data.dispatcher @ events.js:72

**Comment by generationloss** [comment]
I'm having the same issue.  I'm using Rails and serving the videojs-youtube source code to the client using the asset pipeline...it's successfully being delivered, and the video player is being initialized - I see the big play button - but the src comes back as undefined.  I've tried setting it in both the data-setup attribute of the video element and in options block when I initialize the player in the javascript file where I've been doing other video.js customization (adding/removing control bar elements etc).

HTML:
<video controls id="video-player" data-id="<%= @video.id %>" data-duration="<%= @video.duration %>" class="video-js vjs-default-skin" preload="auto" src="" width="100%" height="100%" data-setup='{ "techOrder": ["youtube"], "src": "<%= @video.youtube_url %>"}' data-youtube="<%= @video.youtube_url %>">

JS:
var youTube = $('video').data('youtube');
var vid = videojs($('#video-player')[0], {techOrder: ['youtube'], src: youTube}, function(){})

There are no other errors in the console, until I click play.  Tested in Chrome and Firefox; same result.  Had been using video.js version 4.12; have tested also with 4.6 and 5.0...nothing.  This is driving me nuts...

**Comment by eXon** [comment]
If you're having `techCall_ @ player.js:1148` (with the underscore at the end), you are using VJS5. You have to use the VJS5 branch. However, there is still a major issue VJS needs to fix (there is already a PR for that). 

@generationloss Can you copy the entire error + a crashing example?

**Comment by generationloss** [comment]
@eXon thanks a lot for the quick reply!  I actually solved it...I had videojs-youtube before videojs in my dependencies.  So that was pretty dumb...

**Comment by eXon** [comment]
@generationloss No problem. I'm sure reporting it will help someone else figure out the same :)
