### ISSUE TITLE
How to setup videojs-youtube for VideoJs 5

### ISSUE THREAD

**Issue by Spoowy** [eXon/videojs-youtube#310]
Hey guys,
I've heard that you are currently still working on making videojs-youtube work with videojs 5. Is there something working I can get already? If so, how?

Many thanks.

**Comment by eXon** [comment]
Hey @Spoowy 

VJS5 will be working with videojs-youtube when [this pull request will me merged](https://github.com/videojs/video.js/pull/2339). Until then, you can't use it or it will broken. The code is on the VJS5 branch for now.
