### ISSUE TITLE
Remove native youtube play button

### ISSUE THREAD

**Issue by Spoowy** [eXon/videojs-youtube#311]
![screen shot 2015-09-29 at 17 33 45](https://cloud.githubusercontent.com/assets/6298122/10169257/90b74572-66d0-11e5-9504-d67495adb4e0.png)

How do I remove this button in the middle?

**Comment by eXon** [comment]
On what VJS version are you running?

**Comment by eXon** [comment]
You can't remove the native play button. All the plugin can do is set a poster on top of it. It's how it works by default.

**Comment by Spoowy** [comment]
Ahh cool, that's vjs5 branch :)

**Comment by eXon** [comment]
Vjs 5 is released I will publish it for master. Is it working fine?

**Comment by Spoowy** [comment]
Yes, I didn't have any major issues with it yet

**Comment by Spoowy** [comment]
Will you remove the native play button in the next release?
