### ISSUE TITLE
vjs 5 high quality formats not being displayed

### ISSUE THREAD

**Issue by Spoowy** [eXon/videojs-youtube#312]
![07cded4c-e511-11e4-8a92-4135ba61131d](https://cloud.githubusercontent.com/assets/6298122/10192236/2add0b6e-677b-11e5-95ad-94ec6214de09.png)

Will we also support different video formats in vjs 5? Is this already there and am I overlooking something?

Many thanks

**Comment by eXon** [comment]
I think this should be a plugin. I'm looking with videojs on how we can integrate the video quality concept on tech like YouTube.

**Comment by eXon** [comment]
We should build a plugin just for this. I don't think it should be bundled with the tech.

**Comment by eXon** [comment]
This is out of scope for the tech. I think it should be a plugin.
