### ISSUE TITLE
No video playing

### ISSUE THREAD

**Issue by paulashford1975** [eXon/videojs-youtube#315]
Hi, I am using the latest videojs v5.0.0 on the CDN. I have downloaded the vjs5 branch with the extends->extend fix. Built and included the .min file in the site and used your example src from youtube but there is nothing showing in the player? Thanks Paul

**Comment by PatSpiegel** [comment]
some problem

**Comment by paulashford1975** [comment]
its ok realised my mistake loading the player via angularjs so used a different route
