### ISSUE TITLE
Didnt work

### ISSUE THREAD

**Issue by PatSpiegel** [eXon/videojs-youtube#316]
what do I do not correctly?
http://codepen.io/anon/pen/RWgYYV

**Comment by adamck** [comment]
This plugin doesn't yet work with VJS 5.

**Comment by eXon** [comment]
You can use the VJS5 branch. I haven't published it yet on NPM/Bower.

**Comment by derthiede** [comment]
If you take the code from VJS5 branch you have to fix the call  "var Youtube=videojs.extends" to "var Youtube=videojs.extend" without the "s". Otherwise it won't work with vjs 5.0.0

**Comment by eXon** [comment]
You're right. I'll fix this today. It's been a while VJS5 is now out.

**Comment by eXon** [comment]
Fixed and published as 2.0.0
