### ISSUE TITLE
Update video-js to 5.0.0

### ISSUE THREAD

**Issue by naorye** [eXon/videojs-youtube#317]
I am using video-js v 5.0.0
When npm installing this plugin, I get:
npm ERR! peerinvalid The package video.js@5.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer videojs-youtube@1.2.13 wants video.js@^4.12.5

Please update video-js to 5.0.0.

**Comment by adamck** [comment]
+1 for migrating this to 5.0.

**Comment by eXon** [comment]
Published to 2.0.0
