### ISSUE TITLE
VJS 5 dynamic loading error

### ISSUE THREAD

**Issue by Spoowy** [eXon/videojs-youtube#319]
Hey,
I've been working with the vjs5 branch, so far so good. I'm only getting one error when I load a video dynamically(insert <video...> after pageload with javascript) and click to play(works if video is loaded immediately with pageload).

It's throwing this error in console: Error message: Uncaught TypeError: Cannot read property 'listId' of undefined - vjs.js:139

loadApi() is called
injectCss() is called
window.onYouTubeIframeAPIReady is called
(now clicking on the dynamically created video to play)
createEl() is called
initYTPlayer() is called
throwing error at :139, the video 

this.options value at that stage:
language: "en-us"
playerId: "really-cool-video-VWf8CXwPoqI1"
poster: ""
preload: "auto"
reportTouchActivity: false
source: Object
-> src: "https://www.youtube.com/watch?v=VWf8CXwPoqI"
-> type: "video/youtube"
techId: "really-cool-video-VWf8CXwPoqI1_Youtube_api"

this value:
id_: "no_player_component_8"
name_: null
options_: Object
player_: videojs.extend.constructor

(note: this.url = undefined, this.url.videoId = undefined)

setSrc is not called.

What is something I can do right now to move into the right direction and solve this issue? 

Many thanks!

**Comment by eXon** [comment]
I'm on it. Should be fixed soon.

**Comment by Spoowy** [comment]
For now I've put
```
if (typeof this.url === 'undefined') {
                this.setPoster(this.options_.poster);
                this.setSrc(this.options_.source);
            }
´´´
directly under initYTPlayer: function() {, worked so far :)

quick dirty fix but it did it for me.

**Comment by Spoowy** [comment]
I pulled the new changes and I'm getting now this error when trying to play a video that is created dynamically:

```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."} code: 4message: "The media could not be loaded, either because the server or network failed or because the format is not supported."__proto__: MediaError_logType @ videoCode.js:736log.error @ videoCode.js:736error @ videoCode.js:736handleTechError_ @ videoCode.js:736ret @ videoCode.js:736ret @ videoCode.js:736data.dispatcher @ videoCode.js:736
```

**Comment by neyronius** [comment]
Hi eXon,

i am facing the same problem. Do you have any new updates with this?

Thanks

**Comment by marwanhilmi** [comment]
+1 seeing the same issue sporadically.
```
IDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video
```
Not doing anything fancy - just including the video in our index.html straight up.

**Comment by eXon** [comment]
Are you including video.js / Youtube.js within the head or at the end of the body?

**Comment by marwanhilmi** [comment]
End of body - should move up to head?

**Comment by eXon** [comment]
I'm not sure why but since VJS5 it is working better if you have it inside <head>.

**Comment by Spoowy** [comment]
I'm loading it inside ```<head>```

**Comment by pardeep7387** [comment]
Hi

**Comment by gkatsev** [comment]
I think I'm having a similar issue right now since `initYtPlayer` method doesn't have `this.url` set by the time it is called because `this.setSrc` hasn't been called yet. The way I'm using it right now is as a tech and the html5 tech is loaded up first and then I call `player.src({src:'youtube.com...', type: 'video/youtube'});`. This changes to the youtube tech but it never actually creates the player.

**Comment by pardeep7387** [comment]
thanks for your responce gkatsev.

**Comment by gkatsev** [comment]
I solved my issue by adding `this.initYTPlayer` to  the [setTimeout inside of the constructor](https://github.com/eXon/videojs-youtube/blob/master/src/Youtube.js#L37-L39).
```js
      setTimeout(function() {
        this.initYTPlayer();
        this.el_.parentNode.className += ' vjs-youtube';
      }.bind(this));
```

**Comment by Spoowy** [comment]
Awesome! This solved it!

**Comment by eXon** [comment]
I'll close the issue once this is fixed for real :)

**Comment by NathanSweet** [comment]
This isn't fixed if the player first plays a non-YouTube video (`parentNode` is still null after the `setTimeout`).

**Comment by chenzhutian** [comment]
Yes this isn't fixed if the player first plays a non-YouTube video (parentNode is still null after the setTimeout).
