### ISSUE TITLE
videojs-youtube - v2.0.0 => Which version of video.js?

### ISSUE THREAD

**Issue by ndubbaka** [eXon/videojs-youtube#322]
https://github.com/eXon/videojs-youtube/releases/tag/v2.0.0 isn't working with https://github.com/videojs/video.js/releases/tag/v5.0.0

I am using the code
```
<video
    id="vid1"
    class="video-js vjs-default-skin"
    controls
    autoplay
    width="640" height="264"
    data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}] }'
  >
  </video>
```

**Comment by ndubbaka** [comment]
I get this error on simple.html in examples folder
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('null').
```
![image](https://cloud.githubusercontent.com/assets/545961/10979032/25e58d52-83c8-11e5-8c13-09448c97b8c1.png)

**Comment by eXon** [comment]
It should be working fine with the last video.js 5. The error you are getting is probably because you are not running it on a server.
