### ISSUE TITLE
support for v1.2.*

### ISSUE THREAD

**Issue by faiverson** [eXon/videojs-youtube#328]
videojs 5 has some troubles with ads. So it's important to have a branch working with version 4.
I found a bug (Cannot read property 'setVolume' of undefined) you can see it on (http://fem-inc.com/uitest/viacom.html) and I'd like to make a pull request.

**Comment by andrewevans** [comment]
Has this issue been addressed? Did you go back to videojs 4?

**Comment by eXon** [comment]
Hey! Sorry for the late response. I've created a VJS4 branch you can do a pull request or report a bug.
