### ISSUE TITLE
Plugin not working correctly when video.js is in responsive mode

### ISSUE THREAD

**Issue by roisag** [eXon/videojs-youtube#329]
I've noticed strange YT plugin behavior when videojs v5.x.x is setting up with responsive mode. Using "vjs-16-9" class or even % width container causes youtube plugin stop working correctly. There is only sound. Setting videojs width="640" and it works ok. Testing in IE11 new Opera, Safari, Firefox. Can you confirm my observation?

**Comment by T-L-P** [comment]
hey roisag, i can confirm that behaviour, sadly i have exactly the same problem but no solution so far.

**Comment by T-L-P** [comment]
i found a css fix, maybe it helps for me at least:

    .vjs-16-9
    {
      position: relative !important;
    }

    .vjs-16-9>div:first-child
    {
      position: absolute !important;
      top: 0px;
      left: 0px;
      width:100%;
      height:100%
    }

**Comment by eXon** [comment]
Do you have the same problem with regular mp4 videos with video.js?

**Comment by T-L-P** [comment]
no, mp4 did work well.
the css fix works good so far, didn't test all browsers yet, don't see any problems there.

**Comment by roisag** [comment]
T-L-P, your css fix seems to work quite well.

**Comment by alijaffar** [comment]
:+1: 
Excellent hack, this was pissing me off for quite some time. On another note... is anyone interested in a PHP implementation with an image/brand overlay? I need some help with some planned features check it out http://thea.li/a-custom-video-js-player-with-styling-and-youtube-compatibility

**Comment by clark-stevenson** [comment]
This https://github.com/videojs/video.js/issues/2763 is related.  I am having the same problem with youtube video.  

I will attempt the CSS above. Thanks for sharing it.

**Comment by roisag** [comment]
Related to https://github.com/videojs/video.js/issues/2763 removing instruction from line 58 youtube.js made it work properly. Tested with video.js latest stable release 5.2.4 and seems to work correctly.

**Comment by clark-stevenson** [comment]
Agreed with @roisag. I used that method as well and works fine in all my tests.

**Comment by ktdmedia** [comment]
👍 @T-L-P
