### ISSUE TITLE
YT Native Controls are not displayed

### ISSUE THREAD

**Issue by ulisesrmzroche** [eXon/videojs-youtube#331]
In case you opt to go with youtube native controls, we are setting the controls param to 0, which hides everything, so you can't scrub, play, save, etc. I think the right default should be to show the controls as normal, so we'd need to set it to 1.

Also, show video info is broken as well.

![screenshot 2015-11-18 14 47 32](https://cloud.githubusercontent.com/assets/1151489/11253823/593c7590-8e03-11e5-9f6e-a12c0641a1dc.png)

**Comment by ulisesrmzroche** [comment]
What we want is this: 

![screenshot 2015-11-18 14 49 34](https://cloud.githubusercontent.com/assets/1151489/11253876/9c30b5b4-8e03-11e5-8a86-729e5315a03b.png)

But what we have right now is this

![screenshot 2015-11-18 14 50 05](https://cloud.githubusercontent.com/assets/1151489/11253891/aed266a4-8e03-11e5-932e-3429d02d7adc.png)

I was thinking we could document that if you go with native youtube controls, the views will actually count, albeit as long as you press the play button.

**Comment by eXon** [comment]
I'm not sure to understand your problem. Native controls are wroking fine. What is the steps to reproduce and what is the expected behavior?

**Comment by ulisesrmzroche** [comment]
I made this quite a while ago, and I was working on an earlier version. Right now it seems like everything is working well. Thanks for all your hard work!
