### ISSUE TITLE
Uncaught TypeError: m is not a function

### ISSUE THREAD

**Issue by kalebxyz** [eXon/videojs-youtube#333]
i am using video js /5.0/ wthi youtube plug in and i have tried 5.2.1 but the error is still here i have tried on localhost n server(yahoo ) but no luck ,i keep getting this error on the console ,n video js wont even be displayed i get html 5 player ,with out any video and broken . and i cant install anything on my server its shared hosting with no root access. pls help me !

**Comment by eXon** [comment]
Make sure you have the last version of VJS and videojs-youtube. Then, make sure they both load on your page like in the examples.

Without a way to replicate your bug, there is not much I can do about it.

**Comment by onigetoc** [comment]
I have the same problem, sometime it work, sometime not. if i do F5 or refresh the page it's stop working. Problem with stability on multiple test on multiple website, like this one. 
http://spiritualtv.org/

**Comment by preexo** [comment]
Same happens here with version 5.4.4. Not all the time, just sometimes when refreshing the page.

**Comment by josefbernadi** [comment]
did you pretify the minified code?

this happened to me, because i change the prettify code.
After i change back to original code, it work normally on firefox and chrome
