### ISSUE TITLE
Video loop is not smooth on restart

### ISSUE THREAD

**Issue by LukeCRM** [eXon/videojs-youtube#334]
Hello, I'm trying to use "loop" parameter for a short youtube video to create a fluid video loop, but it seems there's no way to have a smooth start after the first cycle. 
I see some black screen and a sort of load for some milliseconds before the next cycle.

Here's my code:

    <video   id="vid1"  class="video-js vjs-default-skin"  width="640" height="264"
    data-setup='{ 
                     "techOrder": ["youtube"],
                     "sources": [{ "type": "video/youtube",
                     "src" : "https://www.youtube.com/v/vdURoKT1WCQ"}],    
                     "controls": false,
                     "autoplay": true,
                     "preload": true,
                     "loop": true
                }'
    >
    </video>

Can anyone help me?

**Comment by eXon** [comment]
This behavior is controlled by Youtube. Their is not much we can do about it. Do you have the same problem if you use the native controls?

**Comment by LukeCRM** [comment]
Yes I do.
I tried with native controls with no improvement.

I guess it's a Youtube issue so the loop feature won't work smoothly.
A possible solutuion could be moving the current frame at the beginning when the video reaches the end instead of using the loop feature. Thanks anyway for the help.

**Comment by eXon** [comment]
If you have a special use case, you can use the Video.js Javascript API. I don't think it is the default expected behavior though. Thank you for taking the time to report!
