### ISSUE TITLE
Support videojs 5.2 API

### ISSUE THREAD

**Issue by clkao** [eXon/videojs-youtube#335]
Apparently backend tech has a new way to register itself with vjs 5.2:
```
VIDEOJS: WARN: The Youtube tech was registered as a component. It should instead be registered using videojs.registerTech(name, tech)
```

**Comment by clkao** [comment]
It seems [the change](https://github.com/intertwine/videojs-youtube/commit/a1ca8b908f2b566bc64f46340cb8340340c20aec) implements this:

**Comment by intertwine** [comment]
My submit does implement the registerTech change, but be advised, I haven't tested the AMD wrapper with anything but my own code yet, so your mileage may vary.

**Comment by clkao** [comment]
Perhaps you can create a separate PR with the registerTech fix?

**Comment by clkao** [comment]
Note that this API appears to be new in 5.2 only, so if we are to support older version in the mean time, we need to check videojs.VERSION

**Comment by naorye** [comment]
+1

**Comment by Syleron** [comment]
Can we please see the upgrades for the latest version of video.js? CHEERS +1

**Comment by ktdmedia** [comment]
+1

**Comment by eXon** [comment]
This has been fixed. I'm releasing a new version now :)
