### ISSUE TITLE
"Youtube" should be "youtube" in README.md documentation examples

### ISSUE THREAD

**Issue by nick11703** [eXon/videojs-youtube#337]
In the "Options" and "YouTube Controls" documentation in the README.md file, the example code uses "Youtube" in the `data-setup` object when it should be "youtube", all lowercase.

**Comment by eXon** [comment]
Fixed, thanks for reporting it!

**Comment by nick11703** [comment]
It looks like you might have missed one. 
https://github.com/eXon/videojs-youtube/blame/master/README.md#L51

**Comment by eXon** [comment]
Thanks for noticing, it's fixed :)
