### ISSUE TITLE
Uncaught TypeError: videojs.getComponent is not a function

### ISSUE THREAD

**Issue by irfanfadilah** [eXon/videojs-youtube#341]
When I add Youtube.min.js (v2.0.3) it's raise "Uncaught TypeError: videojs.getComponent is not a function"..

The error was in this line: var Tech = videojs.getComponent('Tech');

Did I miss something..?

Additional information: VideoJS (v4.12.15)..

**Comment by eXon** [comment]
You should use the VJS4 branch if you are on the old 4.X

**Comment by tausiffarooqi** [comment]
Hello,

Sorry, I know this thread is closed, but I'm getting the same error even though I'm using version 5.x of video.js. These are the versions I'm using:

    "video.js": "5.4.4",
    "videojs-youtube": "2.0.7"

Can you please provide some help on how to fix this? Thanks!

**Comment by irfanfadilah** [comment]
Hi @tausiffarooqi,

I haven't tried VideoJS v5.x with VideoJS YouTube v2.x yet, but can you make sure the VideoJS YouTube is loaded after VideoJS? And also check (via view page source) if the VideoJS file you use is v5.x,

**Comment by tausiffarooqi** [comment]
@irfanfadilah - Thanks for the reply! Yes, I do have it in the right order. After going through the comments in issue https://github.com/eXon/videojs-youtube/issues/343 I seem to have got it working. I'm now importing the plugins like this:

```javascript
import videojs from 'video.js';
import 'imports?define=>false!videojs-youtube';
```

Previously I had it like this (which wasn't working):

```javascript
import videojs from 'video.js';
import 'videojs-youtube';
```
