### ISSUE TITLE
Uncaught TypeError: this.onerror is not a function

### ISSUE THREAD

**Issue by marianbodisteanu** [eXon/videojs-youtube#345]
Hi.
When "Playback on other Websites has been disabled by the video owner" I get Uncaught TypeError: this.onerror is not a function. It will be good to catch this error before the user clicks play.

**Comment by gine** [comment]
i have the same issue

**Comment by alsar** [comment]
Same here.

**Comment by david-fenton** [comment]
I also get this, but I don't know if this used to be a method or not. It would be nice to see this go away, though.
