### ISSUE TITLE
Fullscreen & AspectRatio

### ISSUE THREAD

**Issue by Guillom** [eXon/videojs-youtube#348]
Hello,

I need the YouTube video to scale/resize fullscreen depending on the browser size or device width.

Actually, I have black borders on screen resize.
Here's my pen : http://codepen.io/blancfonce/pen/obxVXm

Any tips ?
Thx

**Comment by eXon** [comment]
If you want the width/height ratio to always be kept on video.js, you can set the fluid option. I've updated your example here:

http://codepen.io/anon/pen/pgyMxm

This should close https://github.com/videojs/video.js/issues/2935 too :)

**Comment by eXon** [comment]
It seems to work for larger screen, but not for smaller (kinda the whole point). I'll look on what I can do to fix this.

**Comment by Guillom** [comment]
Thanks for your quick response :-)
Ok for the fluid option but i need to scale the video in fullscreen without black borders.

For now i get this result
(have a look at my screen capture)

![scale](https://cloud.githubusercontent.com/assets/11093871/11918024/e1540896-a71f-11e5-943c-606312c1a0a0.jpg)

**Comment by Guillom** [comment]
Un peu comme ça dans l'idée :

**Comment by Guillom** [comment]
I would like to have the video in full screen like this pen: http://codepen.io/ccrch/pen/VYoYOx

**Comment by vaishnavravi33** [comment]
Set data-setup option to true and set the div width and height as per your need. 
It will show video in full size of container div.

```
<div class="full-vid">
    <video id="vid1" class="video-js vjs-default-skin vjs-big-play-centered"
        controls
        width="100%"
        height="100%"
        data-setup='{ 
            "techOrder": ["youtube"],
            "aspectRatio":"16:9", "fluid": true,
            "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=PjGkVCAo8Fw"}]
        }'
      ></video>
</div>
```
