### ISSUE TITLE
Captions by default

### ISSUE THREAD

**Issue by jack7cz** [eXon/videojs-youtube#350]
Hi everyone,

firstly I would like to thank author for this great plugin. Secondly I have problem with captions which doesn´t play by default by youtube videos. MP4 videos are OK, but by youtube videos I have to choose the captions. Is it some kind of bug or I am doing something wrong?

And one more thing - after the video is at the end in the middle of the video shows up YouTube play button.

You can see it here: http://comic.tode.cz/2015/12/23/upoutavka-k-epizode-blood-debts/
pass: comiczone

Thank you very much.

**Comment by alijaffar** [comment]
I don't believe this is supported. What I did for a video was add captions by downloading the vtt or srt file from YouTube, then I used VJS to include it. It's a tedious hack. Example: http://thea.li/the-code

**Comment by eXon** [comment]
There is no plan to support this in the short run. I'll be happy to review a PR if you would like to do it.
