### ISSUE TITLE
Switch control quality video

### ISSUE THREAD

**Issue by Askancy** [eXon/videojs-youtube#351]
Hello I have integrated the script to my site, unfortunately I was not able to enter the switch to control the video quality ..
How can I add it?
```
controls 
preload="auto" 
width="auto" 
height="auto" 
data-setup='{ 
    "techOrder": ["youtube"],
    "aspectRatio":"16:10", 
    "src": "https://www.youtube.com/watch?v={$id_video}",
                    }'>
```

**Comment by eXon** [comment]
The switch on the video quality is not anymore on the YouTube tech because it can't since VJS5. Someone will need to develop a VJS plugin for this.

**Comment by kmoskwiak** [comment]
hope this will help https://github.com/kmoskwiak/videojs-resolution-switcher
