### ISSUE TITLE
Video pauses after setting currentTime

### ISSUE THREAD

**Issue by SeanGrind** [eXon/videojs-youtube#352]
I just updated my video.js and videojs-youtube libraries to the latest (coming from video.js version 4.x) and I've run into an issue when setting the currentTime. 

I've built my own custom controls for the video.js player to handle seeking as well as additional functionality such as rewinding X seconds.  When I determine the new playback time during a seek or rewind I always pause the video, update currentTime, then resume playback (assuming the video was not paused already).  

After the latest update my video will always pause again a split second later.

I tracked down the cause to the changes made in a PR from a couple months ago: https://github.com/eXon/videojs-youtube/commit/9eea6df52ec2870ccf98369eeb26a89b343758b3

There is a flag, *wasPausedBeforeSeek*, that is set at the beginning of setCurrentTime(), which is then used in the onSeeked() function that is called within a timeout triggered 250ms latter.

The problem with this is it assumes the playback state has not changed while the timeout is being performed.  I happen to be setting the player back to play within the 250ms timeout being done so it incorrectly pauses the video again.

I'm not sure what the original issue is this PR was addressing as I cannot find an associated GitHub issue for it so I'm not certain if it's intended behaviour.  It seems to me we should not be making assumptions about the playback state during setCurrentTime(), that should be the responsibility of the caller.  

Based on the commit message from the PR, *Remain paused when paused before seek*, the code to remove the play from lines 233 and 382 should be sufficient to address the issue, however I'm not sure of the full scope of the issue this change was intended to address.  Do you think it would be ok to remove the lines associated with the *wasPausedBeforeSeek* flag?

in setCurrentTime():
```javascript
if (!this.isSeeking) {
   this.wasPausedBeforeSeek = this.paused();
}
```

in onSeeked():
```javascript
if (this.wasPausedBeforeSeek) {
  this.pause();
}
```

**Comment by eXon** [comment]
I can't remove this because it will be breaking some expected behavior. The player should start playing when you seek a new position and you are paused.

Instead, if you seeek and call play on the player, it will detect the play and not pause it again.

**Comment by SeanGrind** [comment]
What expected behaviour would that be?  YouTube does not start playing when you seek to a new position and you are paused; it maintains the current playback state.

**Comment by bansalvks** [comment]
@eXon  could you please post a work around for it?
