### ISSUE TITLE
"Youtube" tech is undefined

### ISSUE THREAD

**Issue by ariasfernando** [eXon/videojs-youtube#354]
Hi! I've installed videojs-youtube from npm, but when I want to show a video, in JS console I get:

VIDEOJS: ERROR: The "Youtube" tech is undefined. Skipped browser support check for that tech.
(from video.js)

TypeError: videojs.registerTech is not a function
(From Youtube.js)

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this video.
(From video.js)

I've wrote HTML and added JS files as says here.

Do you know what could be happening? Thanks!

**Comment by eXon** [comment]
What version of video.js do you have?

**Comment by ariasfernando** [comment]
I'm using v5.4.6

**Comment by eXon** [comment]
Try to upgrade to the last version. I'll try to add a fallback when I have some time for this.

**Comment by ariasfernando** [comment]
That's the last version. Why I'm having this error?

**Comment by eXon** [comment]
It looks like NPM doesn't have the last version. You're having this error because they changed the tech API. I'll fix this soon.

**Comment by ariasfernando** [comment]
videojs.com announces in website that v5.4.6 is the last version available
and which I'm using.
Anyway, please keep me abreast of the fix.

**Comment by baptistebriel** [comment]
I also have this error, using video.js@5.4.6 and videojs-youtube@2.0.8 - any ideas?

**Comment by apatinoyu** [comment]
Also I have this error and I have the:  "video.js": "5.10.1" (Installed by bower)

**Comment by gkatsev** [comment]
I would recommend trying out 2.1.0.
If it's still a problem, can you open a new issue with a [reduced test case](https://css-tricks.com/reduced-test-cases/)?

**Comment by apatinoyu** [comment]
I have: "videojs-youtube": "^2.1.0" and "video.js": "5.10.1",
I see that my error is:     ERROR: The "Youtube" tech is undefined. Skipped browser support check for that tech.

**Comment by apatinoyu** [comment]
Well, I changed to  videojs-youtube/dist/Youtube.js path instead videojs-youtube/dist/Youtube.min.js  and now works! 
The only thing still not working is sometimes when I go back (any view) doesn't load the video Player. I have dispose video too. I'll keep working on this. Thanks for this plugin.

**Comment by adstep** [comment]
Also having this problem using "videojs-youtube": "^2.1.0" and "video.js": "5.11.6",

**Comment by RaoulSchaffranek** [comment]
I can confirm this issue with videojs-youtube: 2.1.1 and video.js: 5.11.9 as well.

**Comment by lvl99** [comment]
I'm currently getting this issue with videojs-youtube@2.1.1 and videojs@5.12.6.

I'm using `browserify` (along with `browserify-shim`) to require `videojs` and `videojs-youtube` into my app. I did some preliminary tests which indicate something funky with the `videojs` object when being required:

In the `/node_modules/videojs-youtube/dist/Youtube.js` file (at the very end):
```javascript
  // Output some tests and details about the Youtube and Tech object
  console.log({
    __: 'videojs-youtube',
    Youtube: Youtube,
    YoutubePrototype: Youtube.prototype,
    Tech: Tech,
    isTech: Tech.isTech(Youtube),
    anotherTechTest: Youtube.prototype instanceof Tech || Youtube instanceof Tech || Youtube === Tech,
    areTechAndPrototypeSame: Youtube.prototype === Tech
  })

  // This is existing code in the Youtube.js file
  // Older versions of VJS5 doesn't have the registerTech function
  if (typeof videojs.registerTech !== 'undefined') {
    videojs.registerTech('Youtube', Youtube);
  } else {
    videojs.registerComponent('Youtube', Youtube);
  }

  // This line here is new, to enable testing in the next file...
  return Youtube;
```

A separate `test.js` file:
```javascript
  var videojs = require('video.js')
  var Youtube = require('videojs-youtube')
  var Tech = videojs.getComponent('Tech')

  console.log({
    __: 'test.js',
    Youtube: Youtube,
    YoutubePrototype: Youtube.prototype,
    isTech: Tech.isTech(Youtube),
    anotherTechTest: Youtube.prototype instanceof Tech || Youtube instanceof Tech || Youtube === Tech,
    areTechAndPrototypeSame: Youtube.prototype === Tech
  })
```

Results:
![image](https://cloud.githubusercontent.com/assets/238480/20530726/9322e5ec-b0d4-11e6-8e55-e40f16cf33f1.png)

You can see in the differing `anotherTechTest` and `isTech` values that may indicate that the `Tech` object/class is not the same reference used in the `test.js` file, therefore the `Tech.isTech` test fails and `videojs-youtube` isn't adequately loaded into the `videojs` class.

**Comment by Zae** [comment]
Any update on this? I'm having the same problems with browserify.

**Comment by johnking** [comment]
Any update on this? I'm having the same problems with electron.

**Comment by than1089** [comment]
This works for me with 
package.json
```
    "video.js": "^7.17.0",
    "videojs-youtube": "^2.6.1",
```

js file, basically videojsYoutube does nothing but initialize Youtube Tech.
```
import videojs from "video.js";
import videojsYoutube from "videojs-youtube";
```
