### ISSUE TITLE
npm run build failing

### ISSUE THREAD

**Issue by anups303** [eXon/videojs-youtube#355]
After doing `npm install` as mentioned in the readme and then running `npm build`, I get the following error
`This fails on your system`
`mkdir -p dist && cp src/Youtube.js dist/Youtube.js && uglifyjs src/Youtube.js -o dist/Youtube.min.js`

Could someone help me in resolving this?

**Comment by eXon** [comment]
what's your OS?

**Comment by anups303** [comment]
Windows 8.1 Professional, 64 bit
