### ISSUE TITLE
Uncaught Error: The "load" method is not available on the playback technology's API

### ISSUE THREAD

**Issue by lwansbrough** [eXon/videojs-youtube#356]
http://jsfiddle.net/mg89ue31

This happens when you call `player.src({})` where the source is of type `video/youtube`.

**Comment by shanepoints** [comment]
I am getting this same error.  The video does seem to load, and it plays as expected, however I run into problems when I try to call the dispose method.

**Comment by shanepoints** [comment]
Nice!  FYI: the dispose issue was totally unrelated :)
