### ISSUE TITLE
"Youtube" tech is undefined

### ISSUE THREAD

**Issue by eat-sleep-code** [eXon/videojs-youtube#359]
I am using the Brightcove-hosted videojs which is version 5.0.9.  I am using the latest version of videojs-youtube.   

I get a _The "Youtube" tech is undefined. Skipped browser support check for that tech._ error when attempting to load a video from YouTube.   .Videos hosted on Brightcove work fine.

Below is a super-scaled-down version of my HTML.   I have 0'd out my account and player IDs for security purposes.  Because of the CMS we use, the scripts have to remain at the bottom of the page.

```
<html>
<head>
</head>
<body>
<video id="videoW-kGosnzvjU" data-account="0000000000000" data-player="000000000" data-embed="default" data-setup='{ "techOrder": ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=W-kGosnzvjU"}] }' class="video-js" controls></video>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script async src="//players.brightcove.net/0000000000000/000000000_default/index.min.js" type="text/javascript"></script>
<script async src="/assets/js/youtube.js" type="text/javascript"></script>
</body>
</html>
``

**Comment by eXon** [comment]
Try to remove the async and move the script in the head. This is because video.js is trying to load the player before the youtube.js script is loaded.

**Comment by gkatsev** [comment]
The other option is to not have the brightcove player / videojs initilize themselves automatically before youtube has finished loading. You'd want initialize the player yourself.

**Comment by gkatsev** [comment]
Closing because I don't think anything is required from videojs-youtube itself. Discussion can continue, though.
