### ISSUE TITLE
Not compatible with latest video.js 5.7.0 ?

### ISSUE THREAD

**Issue by pressaholic** [eXon/videojs-youtube#361]
Hi there,

Thanks for this plugin :)

I installed it with the latest version of Video.js 5.7.0, and i religiously followed your instructions.
But nothing seems to happen.

Is your plugin compatible with video.js 5.7.0 ?

Please help :(

Cheers!

**Comment by eXon** [comment]
I haven't tested lately with the last version. I'll check and let you know.

**Comment by pressaholic** [comment]
Thanks :)



-----------------------------------------------------------------------
*pressaholic*
Wordpress and PHP Web Development
http://pressaholic.com

2016-02-10 18:51 GMT+00:00 Benoit Tremblay <notifications@github.com>:

**Comment by pressaholic** [comment]
Hi there,

Any news about the version issue ?

thanks



-----------------------------------------------------------------------
*pressaholic*
Wordpress and PHP Web Development
http://pressaholic.com

2016-02-10 19:00 GMT+00:00 pressaholic webdev <pressaholic@gmail.com>:

**Comment by s-pc** [comment]
Hi 

First I want to thank you for this great plugin!

I checked and indeed it doesn't work with latest version of VideoJS. Did you check it?

Thanks in advance!

**Comment by gkatsev** [comment]
Latest videojs (5.9.2) and latest videojs-youtube (master) seem to be working together just fine.

**Comment by gkatsev** [comment]
I'm going to close this because the latest version seems to work, if it's still an issue, let us know and we can re-open this.
