### ISSUE TITLE
Will youtube ads show in the player?

### ISSUE THREAD

**Issue by raymestalez** [eXon/videojs-youtube#370]
Hi! I have a question. If a youtube video has enabled the ads, will they show up in the videojs player?

**Comment by eXon** [comment]
It should act exactly like any embedded YouTube video

**Comment by raymestalez** [comment]
Oh, cool, thank you.

**Comment by gkatsev** [comment]
I think this issue can be closed.

**Comment by marianoarga** [comment]
@lumenwrites did you get ads in your videos?, it seems i'm being unlucky
