### ISSUE TITLE
How to disable right click in videojs-youtube

### ISSUE THREAD

**Issue by jprathore** [eXon/videojs-youtube#372]
hi,can anyone give suggestion to disable right click on youtube

**Comment by gkatsev** [comment]
After a quick search, it seems like youtube doesn't allow you to change this in the API.
Probably what you want is to add a transparent div in front of the youtube player's iframe to prevent mouse events from reaching the youtube iframe.

**Comment by gkatsev** [comment]
Closing because there probably won't be any changes made in videojs-youtube.
