### ISSUE TITLE
Players stop working. Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by wegorich** [eXon/videojs-youtube#377]
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://www.youtube.com') does not match the recipient window's origin ('https://www.youtube.com').

Have no idea how to fix it.

I also tryied, to fix iframe source on fly, but have no success.

```
            var interval = setInterval(()=> {
                var url = $('#player_Youtube_api').prop('src');
                if (url && url.match('^http://')) {
                    clearInterval(interval);

                    $('#player_Youtube_api').prop('src', url.replace(/^http:\/\//i, 'https://'));
                    this.onPlayerReady.bind(this);
                }
                else {
                    if (url) {
                        clearInterval(interval);
                        this.onPlayerReady.bind(this);
                    }
                }
            }, 10);
```

**Comment by wegorich** [comment]
Holly fix, I setup local https server, to make this works :+1: Holly google.

**Comment by gkatsev** [comment]
Yeah, testing video players from the file system (when the url is something like `file:///...` is generally not going to work in a lot of cases. It's often best to use a local web server to serve the files.
I guess this issue can be closed now.
