### ISSUE TITLE
set of youtube tech and plugins issues

### ISSUE THREAD

**Issue by narration-sd** [eXon/videojs-youtube#384]
@gkatsev, very nice to see you in here swinging for the fences, as am sure many others also appreciate.

I made a long comment here recently, which should give a further picture of state, only later noticed I'd responded to a closed issue. Can  you use it from here, or  should I copy/paste/edit for standalone new issue?

https://github.com/eXon/videojs-youtube/issues/98

**Comment by gkatsev** [comment]
I guess we should leave it there, hopefully, we can get it re-opened soon.

**Comment by gkatsev** [comment]
So, I read of what you posted in your [comment](https://github.com/eXon/videojs-youtube/issues/98#issuecomment-214651134) on #98, it seems you're having several issues.
Seems like the main issue you're having #371? Are you having issues with videojs-youtube without the time-offset plugin?
If fullscreen is still a problem, we should re-open #98, for the other issues, it would be good if you can open separate issues per problem you're seeing. It would be great if you can also provide [reduced test cases](https://css-tricks.com/reduced-test-cases/) for each one.

**Comment by gkatsev** [comment]
I'm going to close this issue because it's more of a meta/discussion issue and doesn't directly translate to work itself. We definitely should continue discussion here if necessary, though, otherwise, we should discuss each problem in their own issues.

**Comment by narration-sd** [comment]
Hi Gary, definitely the wisest.

I'll split up,the issues, etc., and surely forgo the frustration felt a that moment.

To say more clearly ahead of this, I have a solution for the videos-time-offset plugin and will get that into shape for a pull request as can.

Thus the one that really needs the attention I think is the posters-with-iOS-able-to-start issue.  That's the one where looking over jwplayer's shoulder may be useful.

Thanks again for stepping in here - and to eXon for doing what he could to keep things together.

Best,
Clive
